fgms_question_survey:
    path: /survey/{token}/
    defaults: { _controller: FanFerretQuestionBundle:Survey:survey }
fgms_question_survey_finish:
    path: /survey/{token}/finish/
    defaults: { _controller: FanFerretQuestionBundle:Survey:finish }
fgms_question_notification_seen:
    path: /notification/{token}/
    defaults: { _controller: FanFerretQuestionBundle:Notification:seen }
fgms_question_admin_delivery:
    path: /admin/{property}/{survey}/delivery
    defaults: { _controller: FanFerretQuestionBundle:Admin:delivery, group: null }
fgms_question_admin_delivery_group:
    path: /admin/{group}/{property}/{survey}/delivery
    defaults: { _controller: FanFerretQuestionBundle:Admin:delivery }
fgms_question_admin_comment_cards:
    path: /admin/{property}/{survey}/comment-cards/{page}/{perpage}
    defaults: { _controller: FanFerretQuestionBundle:Admin:commentCards, group: null, page: 1, perpage: 50 }
fgms_question_admin_comment_cards_group:
    path: /admin/{group}/{property}/{survey}/comment-cards/{page}/{perpage}
    defaults: { _controller: FanFerretQuestionBundle:Admin:commentCards, page: 1, perpage: 50 }
