fgms_question_survey:
    path: /survey/{token}/
    defaults: { _controller: FanFerretQuestionBundle:Default:survey }
fgms_question_survey_finish:
    path: /survey/{token}/finish/
    defaults: { _controller: FanFerretQuestionBundle:Default:finish }
