fgms_question_survey:
    path: /survey/{token}/
    defaults: { _controller: FanFerretQuestionBundle:Survey:survey }
fgms_question_survey_finish:
    path: /survey/{token}/finish/
    defaults: { _controller: FanFerretQuestionBundle:Survey:finish }
fgms_question_notification_seen:
    path: /notification/{token}/
    defaults: { _controller: FanFerretQuestionBundle:Notification:seen }
fgms_question_admin_delivery:
    path: /admin/{slug}/delivery
    defaults: { _controller: FanFerretQuestionBundle:Admin:delivery, sluggroup: null }
fgms_question_admin_delivery_group:
    path: /admin/{sluggroup}/{slug}/delivery
    defaults: { _controller: FanFerretQuestionBundle:Admin:delivery }
