services:
#    fan_ferret_question.example:
#        class: FanFerret\QuestionBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    fan_ferret_question.token_generator:
        class: FanFerret\QuestionBundle\Utility\RandomTokenGenerator
        arguments: [128]
