<?php

namespace FanFerret\QuestionBundle\Repository;

/**
 * AclRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AclRepository extends \Doctrine\ORM\EntityRepository
{
}
