<?php

namespace QuestionBundle\Repository;

/**
 * QuestionGroupTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionGroupTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
