<?php

namespace FanFerret\QuestionBundle\Repository;

/**
 * QuestionGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
