<?php

namespace FanFerret\QuestionBundle\Repository;

/**
 * SurveySessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveySessionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Attempts to retrieve the SurveySession
     * which has a particular token.
     *
     * @param string $token
     *
     * @return SurveySession|null
     */
    public function getByToken($token)
    {
        $qb = $this->createQueryBuilder('ss')
            ->andWhere('ss.token = :token')
            ->setParameter('token',$token)
            ->setMaxResults(1);
        $q = $qb->getQuery();
        $arr = $q->getResult();
        if (count($arr) !== 1) return null;
        return $arr[0];
    }

    /**
     * Attempts to retrieve all SurveySession entities
     * which are not completed, have a certain number of
     * notifications, and whose last notification was sent
     * a certain amount of time ago.
     *
     * If the number of notifications is zero then the
     * time will be measured since checkout.
     *
     * @param int $count
     * @param DateInterval|null $since
     *
     * @return array
     */
    public function getByNotification($count, \DateInterval $since = null)
    {
        //  Sanity check arguments
        if ($count < 0) throw new \InvalidArgumentException(
            'Negative count'
        );
        //  Build query
        $qb = $this->createQueryBuilder('ss');
        $count_expr = $qb->expr()->count('sn.id');
        $having_count_expr = $qb->expr()->eq($count_expr,$count);
        $completed_expr = $qb->expr()->isNull('ss.completed');
        $qb->leftJoin('ss.surveyNotifications','sn')
            ->andWhere($completed_expr)
            ->addGroupBy('ss.id')
            ->andHaving($having_count_expr);
        //  Handle date/time constraint
        if (!is_null($since)) {
            //  Sanity check
            $now = new \DateTime();
            $when = clone $now;
            $when->sub($since);
            if ($when->getTimestamp() > $now->getTimestamp()) throw new \InvalidArgumentException(
                '$since is negative interval'
            );
            //  Add to query
            if ($count === 0) {
                $since_expr = $qb->expr()->lte('ss.checkout',':when');
                $qb->andWhere($since_expr);
            } else {
                $max_expr = $qb->expr()->max('sn.sent');
                $having_max_expr = $qb->expr()->lte($max_expr,':when');
                $qb->andHaving($having_max_expr);
            }
            $qb->setParameter('when',$when);
        }
        //  Execute query
        $q = $qb->getQuery();
        return $q->getResult();
    }

    /**
     * Attempts to retrieve a page of SurveySession entities
     * from the data store.
     *
     * @param Survey $survey
     *  The Survey entity whose SurveySession entities shall be
     *  retrieved.
     * @param Page $page
     *
     * @return array
     */
    public function getPage(\FanFerret\QuestionBundle\Entity\Survey $survey, \FanFerret\QuestionBundle\Utility\Page $page)
    {
        $qb = $this->createQueryBuilder('ss');
        $where_expr = $qb->expr()->eq('s.id',':sid');
        $qb->innerJoin('ss.survey','s')
            ->orderBy('ss.checkout','desc')
            ->andWhere($where_expr)
            ->setParameter('sid',$survey->getId());
        $page->addToQueryBuilder($qb);
        $q = $qb->getQuery();
        return $q->getResult();
    }
}
