<?php

namespace FanFerret\QuestionBundle\Repository;

/**
 * SurveySessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveySessionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Attempts to retrieve the SurveySession
     * which has a particular token.
     *
     * @param string $token
     *
     * @return SurveySession
     */
    public function getByToken($token)
    {
        $qb = $this->createQueryBuilder('ss')
            ->andWhere('ss.token = :token')
            ->setParameter('token',$token)
            ->setMaxResults(1);
        $q = $qb->getQuery();
        $arr = $q->getResult();
        if (count($arr) !== 1) return null;
        return $arr[0];
    }

    /**
     * Attempts to retrieve all SurveySession entities
     * which have a certain number of notifications.
     *
     * @param int $count
     *
     * @return array
     */
    public function getByNotificationCount($count)
    {
        $qb = $this->createQueryBuilder('ss');
        $count_expr = $qb->expr()->count('sn.id');
        $having_expr = $qb->expr()->eq($count_expr,$count);
        $qb->leftJoin('ss.surveyNotifications','sn')
            ->addGroupBy('ss.id')
            ->andHaving($having_expr);
        $q = $qb->getQuery();
        return $q->getResult();
    }
}
