<?php

namespace QuestionBundle\Repository;

/**
 * SurveyNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
