<?php

namespace QuestionBundle\Repository;

/**
 * SurveyTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
