<?php

namespace FanFerret\QuestionBundle\Repository;

/**
 * SurveyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Attempts to retrieve the Survey which has
     * a particular slug.
     *
     * @param array $slug
     *
     * @return Survey|null
     */
    public function getBySlug(array $slug)
    {
        $c = count($slug);
        if (($c < 2) || ($c > 3)) throw new \InvalidArgumentException(
            'Expected $slug to be at least 2 and at most 3 elements'
        );
        $qb = $this->createQueryBuilder('s');
        $i = ($c === 3) ? 1 : 0;
        $qb->leftJoin('s.property','p')
            ->leftJoin('p.group','g')
            ->andWhere($qb->expr()->eq('p.slug',':pslug'))
            ->andWhere($qb->expr()->eq('s.slug',':sslug'))
            ->setParameter('pslug',$slug[$i])
            ->setParameter('sslug',$slug[$i + 1]);
        if ($c === 3) {
            $qb->andWhere($qb->expr()->eq('g.slug',':gslug'))
                ->setParameter('gslug',$slug[0]);
        } else {
            $qb->andWhere($qb->expr()->isNull('g.slug'));
        }
        $q = $qb->getQuery();
        $arr = $q->getResult();
        if (count($arr) === 0) return null;
        if (count($arr) !== 1) throw new \RuntimeException('Expected slug to uniquely identify Survey entity');
        return $arr[0];
    }
}
